### ISSUE TITLE
Pre-fetching content

### ISSUE THREAD

**Issue by thibmeu** [blockchainworkbench/workbench-ui#15]
The current website displays a lot of loading screens.
It could help to pre-fetch content. For instance, the next and previous page in a course.

**Comment by severus-sn4pe** [comment]
@thibmeu regarding the caching, we could store content in `localStorage`. or did you have something else in mind?

**Comment by thibmeu** [comment]
You can simply pre-fetch with `window.fetch(url)` the content and let browser caching handle it.
I think this solution is more adequate considering the content may have to be updated.
