### ISSUE TITLE
Modify bulma step when changing page

### ISSUE THREAD

**Issue by thibmeu** [blockchainworkbench/workbench-ui#5]
On exercises pages, the current step of the progress bar should match the current page.

![screenshot_2018-12-14 blockchain workbench](https://user-images.githubusercontent.com/1894894/50003624-2c6b2300-ff9c-11e8-82b0-b1f4a0103474.png)

**Comment by severus-sn4pe** [comment]
Initial implementation of this feature is in PR #8
