### ISSUE TITLE
Page Completion with Quiz and Exercises

### ISSUE THREAD

**Issue by severus-sn4pe** [blockchainworkbench/workbench-ui#57]
What has to be done to track page-completion for each user

**Generation of jsonfeed:**
- Exercises: 
    - [x] ~deploying exercises and store in db with solution-hash as identifier, get exercise-id in return~
- Quiz:
    - ~store mcq in db, hash of [question+answers] as identifier~
    - [x] store quiz in db with a hash of all mcq's belonging to quiz
    - [x] store mapping of exercises and quizzes to page (hash of url as id?) in db
		
**User studying on site:**
- Exercises: 
    - [x] ~complete, deploy on chain, send addr to api, api checks, store result of completion in db, exercise is now marked in db as completed by user~
- Quiz:
    - ~when answering a Question correct, mcq gets marked in db as completed by user~
    - [x] when finishing last question of quiz, quiz gets marked in db as completed by user
    - [x] when user reloads page with quiz, completed quiz shows "you already completed this quiz. [button try again]"

**Check if user has completed a page:**
- [x] request to api with page-url (or hash of it), api checks if user has completed each quiz and exercise of that page, returns true or false
- ~alternatively: on login, user gets a list of already completed pages, so he doesn't have to check api for each page~
		
**More Improvements for the future:**
- handling question validation on server-side
    - hash of right answers[] is stored in db and has to be sent to api in order to check if mcq is answered right.
    - information whether answer is correct or not is no longer stored in jsonfeed, no cheating possible
    - when user answers a question, hash of selected answers is sent to api, checked, marked if correct and response to client

**Comment by thibmeu** [comment]
This looks more like a milestone than a simple issue. This can be splitted in multiple issues on specific repos (some comments are more for the api repository).

**Generation of jsonfeed**
Quiz:
 + store mapping of exercises and quizzes to page -> page already has an id, no need to find a particular hash/unique identifier. This can be a foreign key

**User studying on site**
Quiz:
 + No need to overcomplicate validation by validating every question. Validating the form should be enough.

**Check if user has completed a page**
I would favor the first option, it looks more modular.

**More improvement**

Regarding quiz validation, I would not do it on server side but rather using a zero knowledge based approach. This would keep the certificate system identical to what is already happening for contracts.

**Comment by severus-sn4pe** [comment]
> * No need to overcomplicate validation by validating every question. Validating the form should be enough.

I'm not sure I understand what you mean. Client has just to send a request to api like "I completed quiz xy"? so you would not do it for every question then?

Currently, it's possible to have `mcq` blocks without an `quiz` block. we should then change it, so questions have to have a surrounding `quiz`-block.
